[project]
dynamic = ["version"]
name = "mz-das"
description = "Dictionary As Struct"
authors = [{ name = "Marza Animation Planet", email = "info@marza.com" }]
readme = "README.md"
license = { file = "LICENSE" }
dependencies = ["Qt.py~=1.4.1", "deepdiff~=8.4.2"]
requires-python = ">=3.9"

[project.urls]
Repository = "https://github.com/marza-animation-planet/das"

[project.scripts]
dasadd = "das.tools.dasadd:main"
dasedit = "das.tools.dasedit:main"
daseval = "das.tools.daseval:main"
dasget = "das.tools.dasget:main"
dasrm = "das.tools.dasrm:main"
dasset = "das.tools.dasset:main"

[tool.hatch.version]
path = "python/das/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["python/das"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"